function [ExportFig,ExportFigAxes]=Trace_Plotter(FigName,TraceDir,TraceData,TraceInfo,Highlights,HorzScaleBuffer,VertScaleBuffer,TraceFigSize,ExportOption)
    
    fprintf(['Exporting: ',FigName,'...'])
    warningstatus=warning;
    warning off
    NumRows=size(TraceData,1);
    if ~isfield(TraceInfo,'PlotRange')
        for r=1:NumRows
            TraceInfo(r).PlotRange=[1:length(TraceData(1,1).Trace.YData)];
        end
    end
    if ~isfield(TraceInfo,'Markers')
        for r=1:NumRows
            TraceInfo(r).Markers=[];
        end
    end    
    for r=1:NumRows
        TraceGroup(r).XMax=0;
        TraceGroup(r).XMin=100000000000;
        TraceGroup(r).YMax=0;
        TraceGroup(r).YMin=100000000000;
        TraceGroup(r).Count=0;
        for s=1:size(TraceData(r,:),2)
            if ~isempty(TraceData(r,s).Trace)
                TraceGroup(r).Count=TraceGroup(r).Count+1;
                TraceGroup(r).XMax=max([TraceGroup(r).XMax,max(TraceData(r,s).Trace.XData(TraceInfo(r).PlotRange))]);
                TraceGroup(r).XMin=min([TraceGroup(r).XMin,min(TraceData(r,s).Trace.XData(TraceInfo(r).PlotRange))]);
                TraceGroup(r).YMax=max([TraceGroup(r).YMax,max(TraceData(r,s).Trace.YData(TraceInfo(r).PlotRange))]);
                TraceGroup(r).YMin=min([TraceGroup(r).YMin,min(TraceData(r,s).Trace.YData(TraceInfo(r).PlotRange))]);
            end
        end
        for m=1:length(TraceInfo(r).Markers)
            switch TraceInfo(r).Markers(m).MarkerType
                case 'Point'
                    for n=1:length(TraceInfo(r).Markers(m).XData)
                        %if any(TraceInfo(r).Markers(m).XData(n)==TraceInfo(r).PlotRange)
                            TraceGroup(r).YMax=max([TraceGroup(r).YMax,max(TraceInfo(r).Markers(m).YData(n))]);
                            TraceGroup(r).YMin=min([TraceGroup(r).YMin,min(TraceInfo(r).Markers(m).YData(n))]);
                        %end
                    end
                case 'HorzLine'
                    for n=1:length(TraceInfo(r).Markers(m).XData)
                        %if any(TraceInfo(r).Markers(m).XData{n}(1)==TraceInfo(r).PlotRange)
                            TraceGroup(r).YMax=max([TraceGroup(r).YMax,max(TraceInfo(r).Markers(m).YData{n})]);
                            TraceGroup(r).YMin=min([TraceGroup(r).YMin,min(TraceInfo(r).Markers(m).YData{n})]);
                        %end
                    end
                case 'VertLine'
                    for n=1:length(TraceInfo(r).Markers(m).XData)
                        %if any(TraceInfo(r).Markers(m).XData{n}(1)==TraceInfo(r).PlotRange)
                            TraceGroup(r).YMax=max([TraceGroup(r).YMax,max(TraceInfo(r).Markers(m).YData{n})]);
                            TraceGroup(r).YMin=min([TraceGroup(r).YMin,min(TraceInfo(r).Markers(m).YData{n})]);
                        %end
                    end
                case 'Raster'
                    for n=1:length(TraceInfo(r).Markers(m).XData)
                        %if any(TraceInfo(r).Markers(m).XData{n}(1)==TraceInfo(r).PlotRange)
                            TraceGroup(r).YMax=max([TraceGroup(r).YMax,max(TraceInfo(r).Markers(m).YData{n})]);
                            TraceGroup(r).YMin=min([TraceGroup(r).YMin,min(TraceInfo(r).Markers(m).YData{n})]);
                        %end
                    end
                case 'Patch'
                    for n=1:length(TraceInfo(r).Markers(m).XData)
                        %if any(TraceInfo(r).Markers(m).XData{n}(1)==TraceInfo(r).PlotRange)
                            TraceGroup(r).YMax=max([TraceGroup(r).YMax,max(TraceInfo(r).Markers(m).YData{n})]);
                            TraceGroup(r).YMin=min([TraceGroup(r).YMin,min(TraceInfo(r).Markers(m).YData{n})]);
                        %end
                    end
            end
        end
        
        TraceGroup(r).YMax=TraceGroup(r).YMax+abs(TraceGroup(r).YMax-TraceGroup(r).YMin)*0.02;
        TraceGroup(r).YMin=TraceGroup(r).YMin-abs(TraceGroup(r).YMax-TraceGroup(r).YMin)*0.02;
    end

    ExportFig=figure('name',FigName);
    TempVertPos=1;
    for r=1:NumRows
        ExportFigAxes(r)=subtightplot(NumRows,1,r,[0,0],[0,0],[0,0]);
        hold on
        TempLegend=[];
        LegendCount=0;
        for m=1:length(TraceInfo(r).Markers)
            LegendCount=LegendCount+1;
            TempLegend{LegendCount}=TraceInfo(r).Markers(m).Label;
            switch TraceInfo(r).Markers(m).MarkerType
                case 'Point'
                        plot(-100,...
                            -100,...
                            TraceInfo(r).Markers(m).MarkerLineStyle,...
                            'markersize',TraceInfo(r).Markers(m).MarkerSize,...
                            'markerfacecolor',TraceInfo(r).Markers(m).MarkerFaceColor,...
                            'color',TraceInfo(r).Markers(m).Color);
                case 'HorzLine'
                        plot(-100,...
                            -100,...
                            TraceInfo(r).Markers(m).MarkerLineStyle,...
                            'markersize',TraceInfo(r).Markers(m).MarkerSize,...
                            'linewidth',TraceInfo(r).Markers(m).LineWidth,...
                            'color',TraceInfo(r).Markers(m).Color)
                case 'VertLine'
                        plot(-100,...
                            -100,...
                            TraceInfo(r).Markers(m).MarkerLineStyle,...
                            'markersize',TraceInfo(r).Markers(m).MarkerSize,...
                            'linewidth',TraceInfo(r).Markers(m).LineWidth,...
                            'color',TraceInfo(r).Markers(m).Color)
                case 'Raster'
                        plot(-100,...
                            -100,...
                            TraceInfo(r).Markers(m).MarkerLineStyle,...
                            'markersize',TraceInfo(r).Markers(m).MarkerSize,...
                            'linewidth',TraceInfo(r).Markers(m).LineWidth,...
                            'color',TraceInfo(r).Markers(m).Color)
                case 'Patch'
                        patch([-100,-100,-100,-100],...
                            [-100,-100,-100,-100],...
                            TraceInfo(r).Markers(m).Color,...
                            'markersize',TraceInfo(r).Markers(m).MarkerSize,...
                            'LineStyle',TraceInfo(r).Markers(m).MarkerLineStyle,...
                            'EdgeColor',TraceInfo(r).Markers(m).EdgeColor,...
                            'LineWidth',TraceInfo(r).Markers(m).LineWidth,...
                            'FaceAlpha',TraceInfo(r).Markers(m).Alpha)
            end
        end
        for s=1:TraceGroup(r).Count
            LegendCount=LegendCount+1;
            TempLegend{LegendCount}=TraceData(r,s).Label;
            plot(-100,...
                -100,...
                TraceData(r,s).Trace.LineStyle,...
                'color',TraceData(r,s).Trace.Color,...
                'linewidth',TraceData(r,s).Trace.LineWidth)
        end
        for m=1:length(TraceInfo(r).Markers)
            switch TraceInfo(r).Markers(m).MarkerType
                case 'Point'
                    for n=1:length(TraceInfo(r).Markers(m).XData)
                        plot(TraceInfo(r).Markers(m).XData(n),...
                            TraceInfo(r).Markers(m).YData(n),...
                            TraceInfo(r).Markers(m).MarkerLineStyle,...
                            'markersize',TraceInfo(r).Markers(m).MarkerSize,...
                            'markerfacecolor',TraceInfo(r).Markers(m).MarkerFaceColor,...
                            'color',TraceInfo(r).Markers(m).Color)
                    end
                case 'HorzLine'
                    for n=1:length(TraceInfo(r).Markers(m).XData)
                        plot(TraceInfo(r).Markers(m).XData{n},...
                            TraceInfo(r).Markers(m).YData{n},...
                            TraceInfo(r).Markers(m).MarkerLineStyle,...
                            'markersize',TraceInfo(r).Markers(m).MarkerSize,...
                            'linewidth',TraceInfo(r).Markers(m).LineWidth,...
                            'color',TraceInfo(r).Markers(m).Color)
                    end
                case 'VertLine'
                    for n=1:length(TraceInfo(r).Markers(m).XData)
                        plot(TraceInfo(r).Markers(m).XData{n},...
                            TraceInfo(r).Markers(m).YData{n},...
                            TraceInfo(r).Markers(m).MarkerLineStyle,...
                            'markersize',TraceInfo(r).Markers(m).MarkerSize,...
                            'linewidth',TraceInfo(r).Markers(m).LineWidth,...
                            'color',TraceInfo(r).Markers(m).Color)
                    end
                case 'Raster'
                    for n=1:length(TraceInfo(r).Markers(m).XData)
                        plot(TraceInfo(r).Markers(m).XData{n},...
                            TraceInfo(r).Markers(m).YData{n},...
                            TraceInfo(r).Markers(m).MarkerLineStyle,...
                            'markersize',TraceInfo(r).Markers(m).MarkerSize,...
                            'linewidth',TraceInfo(r).Markers(m).LineWidth,...
                            'color',TraceInfo(r).Markers(m).Color)
                    end
                case 'Patch'
                    for n=1:length(TraceInfo(r).Markers(m).XData)
                        patch(TraceInfo(r).Markers(m).XData{n},...
                            TraceInfo(r).Markers(m).YData{n},...
                            TraceInfo(r).Markers(m).Color,...
                            'markersize',TraceInfo(r).Markers(m).MarkerSize,...
                            'LineStyle',TraceInfo(r).Markers(m).MarkerLineStyle,...
                            'EdgeColor',TraceInfo(r).Markers(m).EdgeColor,...
                            'LineWidth',TraceInfo(r).Markers(m).LineWidth,...
                            'FaceAlpha',TraceInfo(r).Markers(m).Alpha)
                    end
            end
            if TraceInfo(r).Markers(m).LabelOn
                text(TraceInfo(r).Markers(m).Label_XData,...
                    TraceInfo(r).Markers(m).Label_YData,...
                    TraceInfo(r).Markers(m).Label,...
                    'Color',TraceInfo(r).Markers(m).Label_Color,...
                    'FontName',TraceInfo(r).Markers(m).Label_FontName,...
                    'FontSize',TraceInfo(r).Markers(m).Label_FontSize,...
                    'HorizontalAlignment',TraceInfo(r).Markers(m).Label_HorizontalAlignment,...
                    'VerticalAlignment',TraceInfo(r).Markers(m).Label_VerticalAlignment...
                    );
            end
        end
        for s=1:TraceGroup(r).Count
            plot(TraceData(r,s).Trace.XData,...
                TraceData(r,s).Trace.YData,...
                TraceData(r,s).Trace.LineStyle,...
                'color',TraceData(r,s).Trace.Color,...
                'linewidth',TraceData(r,s).Trace.LineWidth)
        end
        if ~isempty(Highlights)
            for h=1:length(Highlights)
                [P1,P2,P3,P4,T1]=PlotBox2(...
                    [Highlights(h).X_Coord,Highlights(h).Y_Coord,...
                    Highlights(h).X_Length,Highlights(h).Y_Length],...
                    Highlights(h).LineStyle,Highlights(h).LineColor,Highlights(h).LineWidth,[],[],[]);
            end
        end
        plot([0,-1*TraceInfo(r).Horz_Scale_Length]+TraceGroup(r).XMax,...
            [1,1]*TraceGroup(r).YMax,...
            '-','color','k','linewidth',1)
        text(double(mean([0,-1*TraceInfo(r).Horz_Scale_Length]+TraceGroup(r).XMax)),...
            double([1]*TraceGroup(r).YMax),...
            [num2str(TraceInfo(r).Horz_Scale_Length),TraceInfo(r).Horz_Scale_Label],...
            'color','k','fontsize',TraceInfo(r).FontSize,...
            'horizontalalignment','center','verticalalignment','top')
        plot([1,1]*TraceGroup(r).XMax,...
            [0,-1*TraceInfo(r).Vert_Scale_Length]+TraceGroup(r).YMax,...
            '-','color','k','linewidth',1)
        text(double([1]*TraceGroup(r).XMax),...
            double(mean([0,-1*TraceInfo(r).Vert_Scale_Length]+TraceGroup(r).YMax)),...
            [num2str(TraceInfo(r).Vert_Scale_Length),' ',TraceInfo(r).Vert_Scale_Label],...
            'color','k','fontsize',TraceInfo(r).FontSize,...
            'horizontalalignment','center','verticalalignment','bottom','Rotation',90)
        legend(TempLegend,'location','E','fontsize',TraceInfo(r).FontSize)
        xlim([TraceGroup(r).XMin-abs(TraceGroup(r).XMax-TraceGroup(r).XMin)*HorzScaleBuffer,TraceGroup(r).XMax+abs(TraceGroup(r).XMax-TraceGroup(r).XMin)*HorzScaleBuffer])
        ylim([TraceGroup(r).YMin-abs(TraceGroup(r).YMax-TraceGroup(r).YMin)*VertScaleBuffer,TraceGroup(r).YMax+abs(TraceGroup(r).YMax-TraceGroup(r).YMin)*VertScaleBuffer])
        axis off
        box off
    end
    for r=1:NumRows
        if isfield(TraceInfo,'VertRatio')
            set(ExportFigAxes(r),'units','normalized');
            TempPos=get(ExportFigAxes(r),'position');
            set(ExportFigAxes(r),'position',[TempPos(1),TempVertPos-TraceInfo(r).VertRatio,TempPos(3),TraceInfo(r).VertRatio]);
        end
        TempPos=get(ExportFigAxes(r),'position');
        TempVertPos=TempPos(2);
    end
    set(gcf,'color','w','position',[0 100,TraceFigSize])
    %%%%%%%%%%%%%
    set(ExportFig,'color','w')
    if ~isempty(ExportOption)
        Full_Export_Fig(ExportFig,ExportFigAxes,[TraceDir,FigName],ExportOption)
    end
    fprintf('Finished!\n')

    warning(warningstatus)

end