function PunctaStats=PunctaStatistics(Coord_Values, Pixel_Area, PixelScaleFactor_um_px, BinSize, BinMax)
    Coord_Values=double(Coord_Values);
    if size(Coord_Values,1)>size(Coord_Values,2)
        
    else
        Coord_Values=Coord_Values';
    end
    PunctaStats.Num_Puncta=length(Coord_Values);
    PunctaStats.PixelArea=Pixel_Area;
    PunctaStats.PixelScaleFactor_um_px=PixelScaleFactor_um_px;
    PunctaStats.PixelArea_um2=PunctaStats.PixelScaleFactor_um_px^2;
    PunctaStats.Area_um2=PunctaStats.PixelArea*PunctaStats.PixelArea_um2;
    PunctaStats.Puncta_Density_um2=PunctaStats.Num_Puncta/PunctaStats.Area_um2;
    
    PunctaStats.Sum=sum(Coord_Values);
    PunctaStats.Max=max(Coord_Values);
    PunctaStats.Min=min(Coord_Values);
    PunctaStats.Median=median(Coord_Values);
    PunctaStats.BinSize=double(BinSize);
    PunctaStats.MaxBin=double(BinMax);

    [   PunctaStats.Mean,...
        PunctaStats.STD,...
        PunctaStats.SEM, ~]=...
        Mean_STD_SEM(Coord_Values);
    
    [   PunctaStats.Num_Bins,...
        PunctaStats.Bin_Edges,...
        PunctaStats.Bin_Labels,...
        PunctaStats.Bin_Centers,...
        PunctaStats.Histogram,...
        PunctaStats.Normalized_Histogram,...
        PunctaStats.Cumulative_Histogram,...
        PunctaStats.Normalized_Cumulative_Histogram]=...
        Multi_Histogram(Coord_Values,...
        [0,PunctaStats.MaxBin],PunctaStats.BinSize);
    
end