if exist('myPool')&&myPool.Connected~=0
    disp('Parpool active...')
else
    delete(gcp('nocreate'))
    myPool=parpool;%
end
GPU_Accelerate=0;


QuaSOR_PixelSize_nm=21
AZBoxSize=50;
CenterCoord=[26,26];
AZBox_XData_px=[0:1:AZBoxSize];
AZBox_XData_px=AZBox_XData_px-AZBoxSize/2;
ProfileCoords=[1:1:AZBoxSize+1];
DegreeInterval=1;
DegreeRange=[0:179];
RotationMethod='bicubic';
AZBox_XData_nm=AZBox_XData_px*QuaSOR_PixelSize_nm;


QuaSOR_Gaussian_Filter_Sigma=0
QuaSOR_Gaussian_Filter_Size=5;



QuaSOR_Gaussian_Filter_Sigma=1
QuaSOR_Gaussian_Filter_Size=2*ceil(QuaSOR_Gaussian_Filter_Sigma*2)+QuaSOR_Gaussian_Filter_Sigma;

clear TestGroup
Group=1;
AZ=1;
TestGroup(Group).TestAZs(AZ).All_Location_Coords=[...
    26,26,1;...
    22,22,1;...
    25,28,1;...
    30,26,1;...
    25,25,1;
    ];
AZ=2;
TestGroup(Group).TestAZs(AZ).All_Location_Coords=[...
    24,20,1;...
    20,30,1;...
    25,25,1;...
    ];
AZ=3;
TestGroup(Group).TestAZs(AZ).All_Location_Coords=[...
    22,22,1;...
    23,23,1;...
    30,30,1;...
    25,25,1;...
    ];

Group=2;
AZ=1;
TestGroup(Group).TestAZs(AZ).All_Location_Coords=[...
    40,10,1;...
    10,40,1;...
    8,8,1;...
    45,34,1;...
    40,40,1;...
    ];
AZ=2;
TestGroup(Group).TestAZs(AZ).All_Location_Coords=[...
    38,5,1;...
    5,5,1;...
    45,20,1;...
    ];
AZ=3;
TestGroup(Group).TestAZs(AZ).All_Location_Coords=[...
    8,25,1;...
    25,8,1;...
    25,45,1;...
    45,25,1;...
    ];

MaxImage=0;
MaxPlot=0;
for Group=1:length(TestGroup)
    TestGroup(Group).MeanImage=zeros(AZBoxSize+1);
    TestGroup(Group).TotalNumEvents=0;
    for AZ=1:length(TestGroup(Group).TestAZs)
        [TestGroup(Group).TestAZs(AZ).QuaSOR_Image,~,myPool]=QuaSOR_Map_Maker(myPool,GPU_Accelerate,...
            1,AZBoxSize+1,AZBoxSize+1,...
            TestGroup(Group).TestAZs(AZ).All_Location_Coords,QuaSOR_Gaussian_Filter_Size,QuaSOR_Gaussian_Filter_Sigma,...
            1,0,[],1);
        TestGroup(Group).MeanImage=TestGroup(Group).MeanImage+TestGroup(Group).TestAZs(AZ).QuaSOR_Image;
        TestGroup(Group).TotalNumEvents=TestGroup(Group).TotalNumEvents+size(TestGroup(Group).TestAZs(AZ).All_Location_Coords,1);
    end
    TestGroup(Group).MeanImage=TestGroup(Group).MeanImage/length(TestGroup(Group).TestAZs);

    [   TestGroup(Group).AllProfiles,...
        TestGroup(Group).AllProfiles_Mean,...
        TestGroup(Group).AllProfiles_STD,...
        TestGroup(Group).AllProfiles_SEM]=...
        ImageRotationProfiles(TestGroup(Group).MeanImage,...
        CenterCoord,ProfileCoords,DegreeInterval,DegreeRange,RotationMethod);

    TestGroup(Group).AllProfiles_Mean_Int=...
        trapz(AZBox_XData_nm,...
        TestGroup(Group).AllProfiles_Mean);
    MaxImage=max([MaxImage,max(TestGroup(Group).TestAZs(AZ).QuaSOR_Image(:))]);
    MaxPlot=max([MaxPlot,max(TestGroup(Group).AllProfiles_Mean(:))]);
end
close all
for Group=1:length(TestGroup)

    figure, 
    set(gcf,'units','pixels','position',[100,100,1200,400])
    subplot(1,3,1),imagesc(TestGroup(Group).MeanImage),axis equal tight,caxis([0,MaxImage])
    hold on
    plot([0,AZBoxSize+1],[CenterCoord],':','color','w','linewidth',0.5);
    colorbar
    title('Mean AZ Image')
    subplot(1,3,2),imagesc(TestGroup(Group).AllProfiles),caxis([0,MaxImage])
    xlabel('Profile Distance (px)')
    ylabel('Profile Angle')
    title({['Group ',num2str(Group),' FiltSigma = ',num2str(QuaSOR_Gaussian_Filter_Sigma)];...
        ['#AZs = ',num2str(length(TestGroup(Group).TestAZs)),' # Events = ',num2str(TestGroup(Group).TotalNumEvents)]});
    colorbar
    subplot(1,3,3),plot(AZBox_XData_nm,TestGroup(Group).AllProfiles_Mean,'-'),ylim([0,MaxPlot]);
    ylabel('Mean Rotation Profile of Mean Image')
    xlabel('Profile Distance (nm)')
    title([' Mean Profile Integral = ',num2str(TestGroup(Group).AllProfiles_Mean_Int)])
end


